<?php
defined('BASEPATH') or exit('No direct script access allowed');

class BangunanPuskesmas_Model extends CI_Model
{
    public function tambahData()
    {
        $data = [
            "kode" => $this->session->userdata('kode'),
            "kdb" => $this->input->post('bangunan1', true),
            "klb" => $this->input->post('bangunan2', true),
            "kdh" => $this->input->post('bangunan4', true),
            "tataletak" => $this->input->post('bangunan5', true),
            "pencahayaan" => $this->input->post('bangunan6', true),
            "lebar_koridor" => $this->input->post('bangunan7', true),
            "tingi_langit" => $this->input->post('bangunan8', true),
            "bila_antar" => $this->input->post('bangunan9', true),
            "bangunan_puskesmas" => $this->input->post('bangunan10', true),
            "lambang_puskesmas" => $this->input->post('bangunan11', true),
            "lambang_jauh" => $this->input->post('bangunan12', true),
            "papannama" => $this->input->post('bangunan13', true),
            "posisi_bangunan" => $this->input->post('bangunan14', true),
            "atap_puskesmas" => $this->input->post('bangunan15', true),
            "langit_langit" => $this->input->post('bangunan16', true),
            "material_dinding" => $this->input->post('bangunan17', true),
            "dinding_wc" => $this->input->post('bangunan18', true),
            "dinding_lab" => $this->input->post('bangunan19', true),
            "material_lantai" => $this->input->post('bangunan20', true),
            "lantai_wc" => $this->input->post('bangunan21', true),
            "lebar_bukaan" => $this->input->post('bangunan22', true),
            "lebar_pintu" => $this->input->post('bangunan23', true),
            "pintu_wc" => $this->input->post('bangunan24', true),
            "material_pintu" => $this->input->post('bangunan25', true),
            "wc_disabilitas" => $this->input->post('bangunan26', true),
            "halaman_puskesmas" => $this->input->post('bangunan27', true),
            "drainase" => $this->input->post('bangunan28', true),
            "kursi_tunggu" => $this->input->post('bangunan29', true),
            "meubelair" => $this->input->post('bangunan30', true),
            "tmpt_poster" => $this->input->post('bangunan31', true),
            "tmpt_spanduk" => $this->input->post('bangunan32', true),
            "taman_obat" => $this->input->post('bangunan33', true),
            "bebas_rokok" => $this->input->post('bangunan34', true),
            "bebas_kecoa" => $this->input->post('bangunan35', true),
            "bebas_tikus" => $this->input->post('bangunan36', true),
            "bebas_kucing" => $this->input->post('bangunan37', true),
            "bebas_jentik" => $this->input->post('bangunan38', true),
            "populasi_lalat" => $this->input->post('bangunan39', true),
            "populasi_kecoa" => $this->input->post('bangunan40', true),
            "kir" => $this->input->post('bangunan41', true),
            "ruang_admin" => $this->input->post('bangunan41a', true),
            "ruang_karyawan" => $this->input->post('bangunan41b', true),
            "ruang_kepala" => $this->input->post('bangunan41c', true),
            "ruang_rapat" => $this->input->post('bangunan41d', true),
            "ruang_pendaftaran" => $this->input->post('bangunan42_1', true),
            "ruang_pemeriksaaan" => $this->input->post('bangunan42_2', true),
            "ruang_tindakan" => $this->input->post('bangunan42_3', true),
            "ruang_kia" => $this->input->post('bangunan42_4', true),
            "ruang_khusus" => $this->input->post('bangunan42_5', true),
            "ruang_gigi" => $this->input->post('bangunan42_6', true),
            "ruang_kie" => $this->input->post('bangunan42_7', true),
            "ruang_farmasi" => $this->input->post('bangunan42_8', true),
            "ruang_resep" => $this->input->post('bangunan42_9a', true),
            "ruang_racik" => $this->input->post('bangunan42_9b', true),
            "ruang_obat" => $this->input->post('bangunan42_9c', true),
            "ruang_konseling" => $this->input->post('bangunan42_9d', true),
            "ruang_bmhp" => $this->input->post('bangunan42_9e', true),
            "ruang_arsip" => $this->input->post('bangunan42_9f', true),
            "ruang_persalinan" => $this->input->post('bangunan42_10', true),
            "ruang_pasca" => $this->input->post('bangunan42_11', true),
            "ruang_lab" => $this->input->post('bangunan42_12', true),
            "ruang_kb" => $this->input->post('bangunan42_13a', true),
            "ruang_anak" => $this->input->post('bangunan42_13b', true),
            "ruang_inap" => $this->input->post('bangunan42_14', true),
            "wc" => $this->input->post('bangunan42_15', true),
            "ruang_tunggu" => $this->input->post('bangunan43_1', true),
            "ruang_asi" => $this->input->post('bangunan43_2', true),
            "ruang_steril" => $this->input->post('bangunan43_3', true),
            "ruang_linen" => $this->input->post('bangunan43_4', true),
            "ruang_dapur" => $this->input->post('bangunan43_5', true),
            "ruang_jaga" => $this->input->post('bangunan43_6a', true),
            "gudang_umum" => $this->input->post('bangunan43_7', true),
            "wc_pasien" => $this->input->post('bangunan43_8', true),
            " rumah_dinas " => $this->input->post('bangunan43_9', true),
            "roda_2" => $this->input->post('bangunan43_10', true),
            "roda_4" => $this->input->post('bangunan43_11', true),
            "garasi_ambulan" => $this->input->post('bangunan43_12', true),
            "area_tabung" => $this->input->post('bangunan43_13', true),
            "selain_diatas" => $this->input->post('bangunan43_14', true),
            "ruang_lain" => $this->input->post('bangunan43_15', true)
        ];
        $this->db->insert('bangunan_puskesmas', $data);
    }
    public function check()
    {
        return $this->db->get_where('bangunan_puskesmas', ['kode' => $this->session->userdata('kode')])->row_array();
    }

    public function ubahData()
    {
        $data = [
            "kode" => $this->session->userdata('kode'),
            "kdb" => $this->input->post('bangunan1', true),
            "klb" => $this->input->post('bangunan2', true),
            "kdh" => $this->input->post('bangunan4', true),
            "tataletak" => $this->input->post('bangunan5', true),
            "pencahayaan" => $this->input->post('bangunan6', true),
            "lebar_koridor" => $this->input->post('bangunan7', true),
            "tingi_langit" => $this->input->post('bangunan8', true),
            "bila_antar" => $this->input->post('bangunan9', true),
            "bangunan_puskesmas" => $this->input->post('bangunan10', true),
            "lambang_puskesmas" => $this->input->post('bangunan11', true),
            "lambang_jauh" => $this->input->post('bangunan12', true),
            "papannama" => $this->input->post('bangunan13', true),
            "posisi_bangunan" => $this->input->post('bangunan14', true),
            "atap_puskesmas" => $this->input->post('bangunan15', true),
            "langit_langit" => $this->input->post('bangunan16', true),
            "material_dinding" => $this->input->post('bangunan17', true),
            "dinding_wc" => $this->input->post('bangunan18', true),
            "dinding_lab" => $this->input->post('bangunan19', true),
            "material_lantai" => $this->input->post('bangunan20', true),
            "lantai_wc" => $this->input->post('bangunan21', true),
            "lebar_bukaan" => $this->input->post('bangunan22', true),
            "lebar_pintu" => $this->input->post('bangunan23', true),
            "pintu_wc" => $this->input->post('bangunan24', true),
            "material_pintu" => $this->input->post('bangunan25', true),
            "wc_disabilitas" => $this->input->post('bangunan26', true),
            "halaman_puskesmas" => $this->input->post('bangunan27', true),
            "drainase" => $this->input->post('bangunan28', true),
            "kursi_tunggu" => $this->input->post('bangunan29', true),
            "meubelair" => $this->input->post('bangunan30', true),
            "tmpt_poster" => $this->input->post('bangunan31', true),
            "tmpt_spanduk" => $this->input->post('bangunan32', true),
            "taman_obat" => $this->input->post('bangunan33', true),
            "bebas_rokok" => $this->input->post('bangunan34', true),
            "bebas_kecoa" => $this->input->post('bangunan35', true),
            "bebas_tikus" => $this->input->post('bangunan36', true),
            "bebas_kucing" => $this->input->post('bangunan37', true),
            "bebas_jentik" => $this->input->post('bangunan38', true),
            "populasi_lalat" => $this->input->post('bangunan39', true),
            "populasi_kecoa" => $this->input->post('bangunan40', true),
            "kir" => $this->input->post('bangunan41', true),
            "ruang_admin" => $this->input->post('bangunan41a', true),
            "ruang_karyawan" => $this->input->post('bangunan41b', true),
            "ruang_kepala" => $this->input->post('bangunan41c', true),
            "ruang_rapat" => $this->input->post('bangunan41d', true),
            "ruang_pendaftaran" => $this->input->post('bangunan42_1', true),
            "ruang_pemeriksaaan" => $this->input->post('bangunan42_2', true),
            "ruang_tindakan" => $this->input->post('bangunan42_3', true),
            "ruang_kia" => $this->input->post('bangunan42_4', true),
            "ruang_khusus" => $this->input->post('bangunan42_5', true),
            "ruang_gigi" => $this->input->post('bangunan42_6', true),
            "ruang_kie" => $this->input->post('bangunan42_7', true),
            "ruang_farmasi" => $this->input->post('bangunan42_8', true),
            "ruang_resep" => $this->input->post('bangunan42_9a', true),
            "ruang_racik" => $this->input->post('bangunan42_9b', true),
            "ruang_obat" => $this->input->post('bangunan42_9c', true),
            "ruang_konseling" => $this->input->post('bangunan42_9d', true),
            "ruang_bmhp" => $this->input->post('bangunan42_9e', true),
            "ruang_arsip" => $this->input->post('bangunan42_9f', true),
            "ruang_persalinan" => $this->input->post('bangunan42_10', true),
            "ruang_pasca" => $this->input->post('bangunan42_11', true),
            "ruang_lab" => $this->input->post('bangunan42_12', true),
            "ruang_kb" => $this->input->post('bangunan42_13a', true),
            "ruang_anak" => $this->input->post('bangunan42_13b', true),
            "ruang_inap" => $this->input->post('bangunan42_14', true),
            "wc" => $this->input->post('bangunan42_15', true),
            "ruang_tunggu" => $this->input->post('bangunan43_1', true),
            "ruang_asi" => $this->input->post('bangunan43_2', true),
            "ruang_steril" => $this->input->post('bangunan43_3', true),
            "ruang_linen" => $this->input->post('bangunan43_4', true),
            "ruang_dapur" => $this->input->post('bangunan43_5', true),
            "ruang_jaga" => $this->input->post('bangunan43_6a', true),
            "gudang_umum" => $this->input->post('bangunan43_7', true),
            "wc_pasien" => $this->input->post('bangunan43_8', true),
            " rumah_dinas " => $this->input->post('bangunan43_9', true),
            "roda_2" => $this->input->post('bangunan43_10', true),
            "roda_4" => $this->input->post('bangunan43_11', true),
            "garasi_ambulan" => $this->input->post('bangunan43_12', true),
            "area_tabung" => $this->input->post('bangunan43_13', true),
            "selain_diatas" => $this->input->post('bangunan43_14', true),
            "ruang_lain" => $this->input->post('bangunan43_15', true)
        ];

        $this->db->where('kode', $this->session->userdata('kode'));
        $this->db->update('bangunan_puskesmas', $data);
    }
}
